name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Spring Boot code
      uses: actions/checkout@v4
      with:
        repository: maheshgowdamg/springboot-dockerfile
        path: springboot-dockerfile

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
  Build:
    runs-on: ubuntu-latest
    needs: Checkout
    steps:
    - name: Checkout Spring Boot code
      uses: actions/checkout@v4
      with:
        repository: maheshgowdamg/springboot-dockerfile
        path: springboot-dockerfile
    - name: Build with Maven
      run: |
        cd springboot-dockerfile
        mvn clean package 
  dockersetupbuildxaction:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
  dockerloginaction:
    runs-on: ubuntu-latest
    needs: dockersetupbuildxaction
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
  dockerbuildpushaction:
    runs-on: ubuntu-latest
    needs: dockerloginaction
    steps:
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./springboot-dockerfile
        file: ./springboot-dockerfile/Dockerfile
        push: true
        tags: maheshgowdamg25/springapp:${{ github.sha }}
  actionscheckoutHelm:
    runs-on: ubuntu-latest
    needs: dockerbuildpushaction
    steps:
    - name: Checkout Helm chart repo
      uses: actions/checkout@v4
      with:
        repository: maheshgowdamg/springboot-app
        token: ${{ secrets.GIT_TOKEN }}
        path: helm-repo
  Updateimagetag:
    runs-on: ubuntu-latest
    needs: actionscheckoutHelm
    steps:
    - name: Update Helm chart image tag
      run: |
        sed -i "s/tag: .*/tag: ${{ github.sha }}/" helm-repo/mychart/values.yaml
  commitandpush:
    runs-on: ubuntu-latest
    needs: Updateimagetag
    steps:
    - name: Commit and push changes
      run: |
        cd helm-repo
        git config user.name "maheshgowdamg"
        git config user.email "maheshgowdag29@gmail.com"
        git add mychart/values.yaml
        if ! git diff --cached --quiet; then
          git commit -m "Update image tag"
          git push origin main
        else
          echo "No changes to commit"
        fi
